package.json
Based on some customer feedback this PR tries to clarify the description of the extension so that it is clear this is for the chromium based Edge browser.
* Updated description
* Updated display name
=> Updating package.json to have a clearer description and display name

README.md
Update readme to include link to extension
=> Update README.md to include link to extension

postBuildStep.ts, src/host/polyfills/cssPaddingInline.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Modifying several polyfills to work with the latest version of the code, also leaving existing code for backwards compatibility
Renaming the target file to elementsTreeOutline.css
Renaming the target file to stylesSectionTree.css
Applyting existing transformations to dark theme.
applySelectTabPatch method is changing it's signature. This PR adds the logic to handle the new signature as well as providing backward compatibility with the former signature.
Changes on TabbedPane.js
https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/ui/TabbedPane.js?q=tabbedPane.js+-f:out&sq=package:chromium&g=0&l=1
=> Modifying polyfills to comply with latest changes in the code.

CHANGELOG.md, package.json
This PR updates the version and changelog ready for the next release to the store.
=> Bumping version to 1.0.5

CHANGELOG.md, package.json
This PR updates the version number and changelog for the 1.0.6 release.
=> Bumping version number for release v1.0.6

package-lock.json
Updating indirect dependencies.
=> Bumping dependencies version.

package.json
Adopting new extensionKind attribute (array instead of literal). Fixes #115 
https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
=> Adopting the new extensionKind attribute 

.vscode/launch.json
This PR adds the ability to debug postbuild step configuration, helps to mitigate issues that caused #120
=> Debug postbuild step in launch.json

CONTRIBUTING.md
Fixing some old paths in the Contributing.md file.
=> Fix Contributing.md

CHANGELOG.md, package-lock.json, package.json
Fixing extension version to 1.0.7
Updating dependencies.
=> Incrementing extension and dependencies version.

package-lock.json, package.json, src/devtoolsPanel.test.ts, src/devtoolsPanel.ts, src/test/helpers.ts
Changes:
- Updating vscode-extension-telemetry package
- Using new error reporting function to send error/callstack telemetry
=> Updating error/callstack telemetry reporting

azure-pipelines.yml
Naming all pipeline steps for clarity.
Before:
After:
=> Naming pipeline steps

postBuildStep.ts, src/host/polyfills/textSelection.test.ts, src/host/polyfills/textSelection.ts
Modifying TextSelection polyfill to return null when no text is replaced.  Modifying TextSelection tests to take code from the source file.  Also changing patch target file from elements_module.js to ElementsPanel.js
=> TextSelection polyfill refactor

src/host/polyfills/cssPaddingInline.test.ts, src/host/polyfills/cssPaddingInline.ts
Modifying cssPaddingInline polyfill to return null when no text is replaced. Modifying cssPaddingInline tests to take code from the source file.
=> cssPaddingInline polyfill refactor

package.json
Disabling "Show network panel" by default.
=> Disabling network by default

CONTRIBUTING.md, package-lock.json, package.json, scripts/downloadAndExtractEdge.js
Updating downloadAndExtractEdge.js to include Mac workflow.  The download script will now detect the user's platform, download and extract the appropriate zip for their platform, and output platform-specific lines to set environment variables.
=> [Download Script]: Improving mac contributing workflow

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json
Updating Changelog that reflects the major changes this iteration.
=> [Changelog Update]: Updating changelog to reflect current state (version 83)

CHANGELOG.md, package-lock.json, package.json
Bumping version and updating changelog for 1.1.2 release
=> Bumping version to 1.1.2

README.md
I don't think it makes sense to add a video here, I will do one as a Tweet the next few days.
=> Added a section to the README to set up live reload on you project folder

CONTRIBUTING.md, scripts/downloadAndExtractEdge.js, src/host/polyfills/runtime.ts, src/host/polyfills/simpleView.ts
Changes:
- updated polyfill to work with DevTools version 87.0.668.0
- updated polyfill to work with unminified code
- removed platform differentiating step in download script
=> Update DevTools to version 87.0.668.0

CHANGELOG.md, package-lock.json, package.json
Bumping version in package files and adding changelog for milestone 1.1.3. Closing #251
=> Preparing for 1.1.3 milestone release

CHANGELOG.md, package-lock.json, package.json
This PR updates the extension version to 1.1.4 and updates the `CHANGELOG.md` to reflect the latest changes.  Additionally, I ran `npm install` to update the package-lock.json and committed those changes.
=> [Changelog]: Update to 1.1.4

package-lock.json, package.json
Updating vscode extension manager from 1.79 to 1.85.1
=> Updating vsce from 1.79.5 to 1.85.1

CHANGELOG.md, package-lock.json, package.json
=> [Changelog]: Update to 1.1.5

postBuildStep.ts, src/cdpTarget.ts, src/cdpTargetsProvider.ts, src/common/settingsProvider.ts, src/common/webviewEvents.ts, src/debugTelemetryReporter.ts, src/devtoolsPanel.ts, src/extension.ts, src/host/host.ts, src/host/mainHost.ts, src/host/mainMessaging.ts, src/host/messaging.ts, src/host/polyfills/cssPaddingInline.ts, src/host/polyfills/inspectorContentPolicy.ts, src/host/polyfills/releaseNote.ts, src/host/polyfills/releaseNoteContent.ts, src/host/polyfills/runtime.ts, src/host/polyfills/simpleView.ts, src/host/polyfills/textSelection.ts, src/host/polyfills/thirdPartyI18n.ts, src/host/toolsHost.ts, src/host/toolsResourceLoader.ts, src/host/toolsWebSocket.ts, src/launchDebugProvider.ts, src/panelSocket.ts, src/utils.ts, webpack.config.ts
=> Auto-fixing ESLint issues

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
Updating `CHANGELOG.md`, `package.json` and the release notes to reflect completed work items for version 1.1.8.
[Changelog](https://github.com/microsoft/vscode-edge-devtools/blob/user/milia/1.1.8/CHANGELOG.md#118):
[What's New](https://github.com/microsoft/vscode-edge-devtools/blob/user/milia/1.1.8/src/host/polyfills/releaseNoteContent.ts):
=> [1.1.8 Update]: Updating changelog, package.json and release notes

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
Updating CHANGELOG.md, package.json and the release notes to reflect completed work items for version 1.1.9.
[Changelog](https://github.com/microsoft/vscode-edge-devtools/pull/393/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed):
[What's New](https://github.com/microsoft/vscode-edge-devtools/pull/393/files#diff-43c5bb667c0b2fd7ae8e29688de3e11bf058b6d04a66ae978503bea4cc612030):
=> [1.1.9 Update]: Updating changelog, package.json and release notes

src/cdpTargetsProvider.ts, src/extension.ts, src/launchConfigManager.ts, src/launchDebugProvider.ts, src/utils.ts, test/extension.test.ts, test/launchConfigManager.test.ts, test/utils.test.ts
Waiting on: https://github.com/microsoft/vscode-edge-devtools/pull/372
=> [Launch Config]: Create LaunchConfigManager class to manage launch.json logic

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
Updating CHANGELOG.md, package.json and the release notes to reflect completed work items for version 1.2.0
=> [Update 1.2.0] - updating release notes, changelog, package.json

.github/workflows/main.yml, README.md, azure-pipelines.yml, package.json, src/extension.ts
This PR updates references from the master branch to the main branch in our code's docs and CI references.
=> Update master to main in docs and CI

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
Updating CHANGELOG.md, package.json, and the release notes to reflect included changes to version 1.2.1
Changelog:
Welcome:
=> [Update 1.2.1] - Updating release notes, changelog, package.json

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
This PR updates the version number, release notes, changelog and package.json in preparation for the 1.3.0 release
Legacy bundled welcome tab:
=> [Update 1.3.0] - Updating release notes, changelog, package.json

CHANGELOG.md, package-lock.json, package.json, src/host/polyfills/releaseNoteContent.ts
This PR updates the version number, release notes, changelog and package.json in preparation for the 1.3.1 release.
Legacy
=> Updates to version 1.3.1

src/screencast/emulatedDevices.ts
This PR updates the list of emulated Devices to match the browser DevTools
=> [Screencast] Sync standalone Screencast's device list with in-box Devtools'

package-lock.json, package.json
=> Update vscode-webhint to version 1.6.6

CHANGELOG.md, package-lock.json, package.json
VSIX to be published (zipped to allow upload to GitHub): [vscode-edge-devtools-1.4.7.zip](https://github.com/microsoft/vscode-edge-devtools/files/8422064/vscode-edge-devtools-1.4.7.zip)
=> [Changelog]: Updating to 1.4.7

src/screencast/flyoutMenuComponent.ts
Based on https://lit.dev/docs/templates/directives/#ref
=> Switch to using ref instead of id

package-lock.json, package.json, src/screencast/dimensionComponent.ts, src/screencast/emulatedDeviceHelpers.ts, src/screencast/flyoutMenuComponent.ts, src/screencast/screencast.ts, src/screencast/view.css, src/screencast/view.ts
=> Screencast v2

package.json
This PR updates vscode-webhint to the latest version.
Fix #976
=> Updating webhint version

src/devtoolsPanel.ts, src/screencastPanel.ts, src/utils.ts, test/helpers/helpers.ts
=> Add Edge icon to webviews and s/Screencast/Browser/

src/screencast/dimensionComponent.ts, src/screencast/flyoutMenuComponent.ts, src/screencast/screencast.ts
This patch adds html title attributes to buttons and inputs in the Screencast emulation bar.
=> Add titles to emulation bar members

src/common/settingsProvider.ts, src/devtoolsPanel.ts, test/common/settingsProvider.test.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts, test/utils.test.ts
This setting was already a no-op. Removing to avoid confusion.
=> Remove obsolete network setting and related code

package.json, src/common/settingsProvider.ts, src/devtoolsPanel.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts
This setting was already a no-op. Removing to avoid confusion.
=> Remove obsolete welcome setting and related code

src/screencast/screencast.ts
=> [Screencast] Fix entering https url

README.md, azure-pipelines.yml, src/cdpTargetsProvider.ts, src/extension.ts, src/screencast/input.ts, startpage/index.html, test/cdpTargetsProvider.test.ts
Please inspect removal of /en-us in code listings.
=> Changed docs.microsoft.com to learn.microsoft.com

CHANGELOG.md, package-lock.json, package.json
=> Updating to version 2.1.2

CONTRIBUTING.md, test/helpers/helpers.ts
Cleaning the `CONTRIBUTING.md`  instructions to reflect the current code, also removing some unused-legacy code.
=> Cleaning code for Contributing

src/utils.ts, src/versionSocketConnection.ts
This PR updates the fallback version to 120.0.2210.181
=> Updating fallback version to 120

package-lock.json, package.json
=> Upgrade: Bump puppeteer to v18

.vscode/launch.json, src/devtoolsPanel.ts, src/utils.ts, src/versionSocketConnection.ts
- Updates fallback version to use Edge 127
- Fixes an issues where if the user had a well known version set in the cache it always use that one, even if a new one is present.
Close
=> Updates fallback version

src/utils.ts
=> Fixing typo

package-lock.json, package.json, src/cdpTargetsProvider.ts, src/debugTelemetryReporter.ts, src/devtoolsPanel.ts, src/extension.ts, src/launchDebugProvider.ts, src/screencastPanel.ts, src/utils.ts, test/cdpTargetsProvider.test.ts, test/debugTelemetryReporter.test.ts, test/devtoolsPanel.test.ts, test/extension.test.ts, test/helpers/helpers.ts, test/launchDebugProvider.test.ts, test/utils.test.ts
Upgrading typescript and vscode-extension-telemetry and making changes to support the upgrades
=> Upgrading typescript and vscode-extension-telemetry

src/devtoolsPanel.ts
This PR allows clipboard policies in the webview to allow `WriteText` access, this PR requires a change on the devtools side to fix #2051
=> Allowing clipboard policies for webview
