.vscode/settings.json, README.md, package.json, src/utils.test.ts, src/utils.ts
There have been several reported issues of the extension not working which after investigation have boiled down to the fact that Edge is already open without remote debugging enabled. The issue with this is that when we launch a new instance with the `--remote-debugging-port` flag set it doesn't actually enable remote debugging so the extension fails to attach.
The way the other Chromium debug extensions get around this is by changing their default behavior to use the `--user-data-dir` flag set to a temporary folder. This will force the browser to spin up a new manager process (which will look like a new window) that *does* have remote debugging enabled, and then they can connect to that instance.
This PR replaces the `userDataDirectory` setting with a newer `userDataDir` version that …
=> Adding a default userDataDir setting to match Edge/Chrome debugger behavior

package-lock.json, package.json
This PR updates the vsce package to the latest (1.64.0) to fix the npm audit issue https://nodesecurity.io/advisories/786 .
* Rolling vsce to version 1.64.0
=> Updating vsce npm package

src/utils.ts
Adding 2 new flags to the launch of the browser. These will disable the first launch experience and the check for the default browser. This matches the behavior of the chrome and edge debug extensions and provides a cleaner launch experience for the user.
* Added `--no-first-run` and `--no-default-browser-check` flags to launch
=> Add flags for cleaner edge launch

CHANGELOG.md, package.json
This PR updates the version number to 1.0.1 and adds information to the change log about the most relevant changes that are going into this update. The change log can be seen from the extension marketplace page or from inside VS Code itself.
* Bumped version to 1.0.1
* Updated change log
=> Bumping version to 1.0.1 for next preview release

src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts, src/host/toolsHost.test.ts, src/host/toolsHost.ts
This PR is the first step in the feature to open links from the Elements tool in the VS Code editor (see #55). It adds patch code so that the Elements tool will call into the new openInEditor() function when a user clicks a revealer link. The openInEditor() function sends a message to the extension which is where we will actually open the file. The actual open will be implemented in a later PR.
* Added patch for calling openInEditor from the Elements tool
* Added plumbing for passing request to the extension
* Added placeholder for actual opening functionality
* Updated tests
=> Adding placeholder code for openInEditor function

README.md, package.json, src/utils.test.ts, src/utils.ts
This PR is the second step in the feature to open links from the Elements tool in the VS Code editor (see #55). It adds a number of settings that can be specified by the user in either their `launch.json` or in the extension settings (for when attach/launch is done using the side panel). The actual opening of the files in the Editor will be done in a follow up PR.
The source map settings match those used by the debugger for Edge extension and will be used to map the runtime source locations reported by the browser, such as `http://localhost:8080/app/file.js` to files that exist on disk, such as `build/out/app/file.ts`.
A new function has been added to get the various runtime settings based on the order of presidence:
launch.json > extension settings > default values
* Added new sourcemap …
=> Adding sourcemap related settings ready for opening links in the editor

src/devtoolsPanel.test.ts, src/devtoolsPanel.ts, src/extension.test.ts, src/extension.ts
This PR is the third step in the feature to open links from the Elements tool in the VS Code editor (see #55). It plumbs through the runtime config from the PR #75 to the DevToolsPanel where it will be used to map the devtools link to the editor file on disk so that it can be opened.
* Added new param to DevToolsPanel constructor
* Passing runtimeConfig to the DevToolsPanel via extension.ts
* Added a new telemetry call to record usage for the open in editor feature
* Updated tests to use a mock config and added a new test for the telemetry
=> Pass the runtime config to DevToolsPanel

package-lock.json, package.json, src/common/webviewEvents.ts, src/devtoolsPanel.test.ts, src/devtoolsPanel.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts, src/host/toolsHost.test.ts, src/host/toolsHost.ts, src/host/toolsResourceLoader.test.ts, src/host/toolsResourceLoader.ts, src/test/helpers.ts, src/utils.test.ts, src/utils.ts
This PR adds the final part of the changes to actually open links in the editor. The onSocketOpenInEditor() function now takes the url from the elements tool (which will be the source mapped url if they are enabled) and calls helpers to convert it to the local workspace path using the config settings. 
Fixes #55, #54
Take a look at this animation to see the results:
* Added utils functions to map elements links to vs code file paths (based on the same work in edge debug adapter)
* Added chrome-debug-core package to perform some mapping
* Updated the openInEditor function to actually open the files
* Updated tests and added new ones
=> Actually opening files in editor from links in the elements tool

package-lock.json, package.json
This PR updates the package.json file to use the new format for VS Code extensions from the 1.36.0 update. You can read more about the package changes here:
https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
The PR follows the migration guidance from here: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
* Updated to use the new @types/vscode and vscode-test packages
* Updated to 1.36 VS Code engine version
* Removed diff dev dependency
=> Moving to new vscode package

src/common/webviewEvents.ts, src/devtoolsPanel.test.ts, src/devtoolsPanel.ts, src/panelSocket.ts
This PR bubbles up the close message from the websocket to the extension, so when the websocket is closed the extension will be closed too.
=> Bubbling up close message from websocket to the extension.

CHANGELOG.md, package.json
This PR updates the version number to 1.0.3 and adds information to the change log about the most relevant changes that are going into this update. The change log can be seen from the extension marketplace page or from inside VS Code itself.
Bumped version to 1.0.3
Updated change log
=> Bumping version to 1.0.3 for next preview release

postBuildStep.ts, src/host/host.test.ts, src/host/host.ts, src/host/toolsResourceLoader.ts
Chromium repository migrated to a new repository and a new path, this PR address the following issues caused by this:
- Fixes the path for devtools folder and updates postBuildStep with the new path.
- Fixes an issue caused by moving window.Runtime to window.Root.Runtime
- Fixes an issue caused by session storage not being available for the developer tools as VsCode does not exposes it
- Fixes associated tests
=> Fixing issues caused by chromium devtools repository migration.

package.json, postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Fixing issue #100 
**Root cause:**
There were changes on the devtools code regarding ESM migration. 
**Fix:**
Update the polyfill to match the new version.
=> Fixing issue with Revealer polyfill.

.vscode/launch.json, package.json, postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts, src/test/helpers.ts
This PR does a medium size refactoring on simpleView polyfill that I consider need to expand to the rest of polyfills:
- SimpleView.test.ts
Currently the tests verify that a function can be override by the polyfills. The issue is that the actual content of the file constantly changes. This PR forks the behavior as follows:
- If run in the server: It will continue working as today, verifying that a static text can be patched.
- If run locally: it will verify if the actual files exist in disk, if they do it will run the tests again the file contents, and it will fail if the contents do not match. This will make patching and spotting differences easier by reducing turnaround time
PostBuild.ts:
Currently "Release" and "Debug" mode are treated as one, this creates issues as the files on …
=> SimpleView polyfill refactor

package.json
This PR fixes an issue where the "Attach and open Elements" button in the target list is inaccessible to screen reader users. It visually appears as part of the target treeitem when hovered or focused, but is not read out by screen readers and there's no indication that a button has appeared to tab to. The button is defined in package.json and created by the target list TreeView, so it isn't feasible to reparent it or add aria to help expose it to screen readers.
Since TreeView is a common extension point, there's another Microsoft extension that has had to address this issue--the WSL extension, which solved the problem by putting the action in the context menu as well: 
This way, users can access the button functionality by opening the context menu, rather than by tabbing to a button …
=> Add attach action to context menu

src/extension.ts
Fixing bug where this warning consistently pops up:
This was implemented in [this PR supporting Debugger for Microsoft Edge compatibility](https://github.com/microsoft/vscode-edge-devtools/commit/eec060f343ecabfd55bab9a11267292fb2fd479d).
Before, the code was 
```
if (matches && matches.length > 0 && matches[0].detail) {
targetWebsocketUrl = matches[0].detail;
} else {
vscode.window.showErrorMessage('Couldn't attach to ${attachUrl}.');
}
```
It got changed to
```
if (matchedTargets && matchedTargets.length > 0 && matchedTargets[0].webSocketDebuggerUrl) {
const actualTarget = fixRemoteWebSocket(hostname, port, matchedTargets[0] as any);
targetWebsocketUrl = actualTarget.webSocketDebuggerUrl;
}
if (!useRetry) {
vscode.window.showErrorMessage(`Couldn't attach to ${attachUrl}.`);
}
```
This …
=> Fixing 'Couldn't attach to ...' bug

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
This PR adds the network tool to the devtools extension!  The majority of this change was moving over the various patches and tests unique to the Network tool.
Here are some other notable changes from in this PR:
- Created "applyAppendTabPatch" as the one tabbing patch.  This targets the 'appendTab' function which later funnels into the showTab/selectTab functions that were previously being patched.
- Simplified tests by making variable names consistent and separating tests that were grouped together (some tests has result1, result2, result3...)
- Changed `.tabbed-pane-right-toolbar` patch to be `visibility: hidden` over `display: none` since it was hiding the network search close button and could not reveal when its parent had `display: none`
- Removed …
=> Merging Network Extension

CHANGELOG.md, README.md, package-lock.json, package.json, src/devtoolsPanel.ts, src/launchDebugProvider.ts, src/utils.ts
With the addition of the Network tool from [PR 128](https://github.com/microsoft/vscode-edge-devtools/pull/128), the extension is being renamed from ""Elements for Microsoft Edge (Chromium)"" to "Microsoft Edge (Chromium) Tools for VSCode."
This PR targets the usages of the extension name in the README, config files, package.json and other files.
- Using "Edge DevTools" in more informal cases where appropriate
- "Launch Microsoft Edge and open the Edge DevTools"  here -https://github.com/microsoft/vscode-edge-devtools/pull/134/files#diff-04c6e90faac2675aa89e2176d2eec7d8L88
- Title in the extension tab - https://github.com/microsoft/vscode-edge-devtools/pull/134/files#diff-e1495d267619047a7cca5cfe8f692729R58​​​​​​​
- Generally using "Microsoft Edge Tools" when referring to the extension in …
=> Renaming Extension to "Microsoft Edge (Chromium) Tools for VSCode" + Changelog Update

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
The Quick Open menu is available via (CTRL + P), but the functionality is disabled in the extension.  This PR disables the quick open command so the menu will not pop up.
=> Disabling Quick Open Action (CTRL+P)

src/host/polyfills/simpleView.ts
Fixing issue where the "Inspect Element" was not showing up.
Changes:
- Removed CSS patch that hides the inspect button
=> Unhiding the inspect button

package.json, src/common/tabSettingsProvider.test.ts, src/common/tabSettingsProvider.ts, src/common/webviewEvents.ts, src/devtoolsPanel.test.ts, src/devtoolsPanel.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts, src/host/toolsHost.ts, src/test/helpers.ts
This PR introduces a setting that allows to control whether the "Network" panel should be displayed or not. 
New setting:
When _checked_ the network panel will be displayed.
=> Adding an extension setting that will  toggle network panel on and off

package.json
**Root Cause:**
The default value for browserPath setting is wrong as null is not a valid value.
**Fix:**
Changing it to empty string. I verified that the path that uses this already considers empty === not set
Before:
After:
=> Fixes default value for Browser Path

package.json
**Root cause:**
sourceMapPathOverrides is confusing as it has the same text as pathMapping.
**Fix:**
Provide a more accurate description.
=> Fixing sourceMapPathOverrides description

package.json, src/extension.ts, src/utils.test.ts, src/utils.ts
This PR removes the _browserPath setting_ and creates a _browser flavor combo box_ for a similar purpose.
**Current Behavior:**
The user can specify (via a input box) the path to a browser version, when no path is specified the extension searches for stable > beta > dev > canary (in that order) until an existing version is found on disk.
**New Behavior**
When default is selected, extension will keep current behavior, otherwise it will use the version specified by the user. 
Test are also modified to use a specific flavor instead of a custom path.
=> Converting from browserPath to browserFlavor

azure-pipelines.yml, scripts/pipelineUnzipEdge.sh, scripts/retrieveDownloadLink.js, scripts/unzipEdge.sh
- updating retrieveDownloadLink to accept an argument for which platform
- Adding scripts for windows users and for the pipeline to easily extract from the .zip file
- unzipEdge.sh works best for Windows users downloading the DevTools .zip
- pipelineUnzipEdge.sh performs the same function with minor changes to work in a linux based environment
=> Fix pipeline: Adding platform args to download script and adding unzipping bash script

src/host/polyfills/inspectorContentPolicy.test.ts, src/host/polyfills/inspectorContentPolicy.ts
Modifying inspectorContentPolicy polyfill to return null when no text is replaced. Modifying inspectorContentPolicy tests to take code from the source file.
=> inspectorContentPolicy polyfill refactor

package-lock.json, package.json, src/devtoolsPanel.ts, src/host/host.test.ts, src/host/host.ts, src/host/messaging.test.ts, src/host/messaging.ts, src/host/polyfills/inspectorContentPolicy.test.ts, src/host/polyfills/inspectorContentPolicy.ts
Issue:
Resources were not loaded, which broke the extension
Fix:
Updating some resources with the latest practices for webview.
Related discussion here:
https://github.com/microsoft/vscode/issues/101562
=> Updating some missing webview resources

azure-pipelines.yml
This PR separates Mac and Windows runs in the pipeline.  They download separate zip files and publish the .vsix artifacts to different artifact folders.  An example run can be found [here](https://dev.azure.com/edgedevtools/vscode-edge-devtools-ci/_build/results?buildId=372&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7)
=> [Pipeline]: Adding Mac job to the pipeline

package-lock.json, package.json, src/extension.ts, src/utils.test.ts, src/utils.ts
This PR introduces a new Setting called:
- Headless (off by default)
Which allow the user to use the extension in headless mode. The headless browser tabs will be closed when the associated visual studio code session ends.
Tests are also provided.
Demo:
https://imgur.com/a/qryItHH
Addresses:
#173
=> Introducing "headless" browser launch mode

.vscode/launch.json, postBuildStep.ts, src/host/polyfills/cssPaddingInline.test.ts, src/host/polyfills/cssPaddingInline.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Currently there is a configuration named "debug mode" which targets the source files of the Edge Chromium repo (not the output files). This was done to enable coding with the Devtools source files. Unfortunately this created a dependency to the source files itself (requiring the full 2gb file). This PR removes this dependency, any changes required on Devtools should be done in Devtools repo or patched through a "polyfill"
Addresses #169
=> Removing debug mode.

src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
This PR allows users to click on the mapped files and get the file open in vscode (broken behavior)
**Root cause:**
OpenEditor got broken due to changes in the InspectorHost module on the Devtools side.
**Fix:**
InspectorHost in no longer a global, instead it should be accessed through the legacy mechanism, which maps InspectorHost.Instance() to InspectorHost.
=> Fixing openEditor in simpleView.ts polyfill

CHANGELOG.md, CONTRIBUTING.md, README.md, package.json, postBuildStep.ts, src/extension.ts, src/host/toolsWebSocket.ts, src/test/helpers.ts
- Removing instances of "(Chromium)"
- Adding space between "VS" and "Code"
=> Renaming extension from "Microsoft Edge (Chromium) Tools for VSCode" to "Microsoft Edge Tools for VS Code"

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
DOM Breakpoints operate on the sources pane which is not included in the extension.  This PR removes the DOM Breakpoints tab in the Elements side panel and the "Break on" context menu option
=> Remove DOM Breakpoint tab and context menu option

CONTRIBUTING.md, azure-pipelines.yml, postBuildStep.ts, scripts/downloadAndExtractEdge.js, src/test/helpers.ts
Since we are storing the Edge files within the vscode-edge-devtools directory, we no longer need environment variables and can use relative pathing.  This PR removes the need for `EDGE_CHROMIUM_PATH` and `EDGE_CHROMIUM_OUT_DIR` environment variables.
=> [Contributing]: Removing environment variable from setup process

src/host/host.ts
Mac meta key (command key) is not propagated out of the DevTools IFrame.  This change creates a keydown listener inside the iframe to execute shortcut commands using the meta key.
Functionalities include:
- copy ( meta + C )
- cut ( meta + X )
- paste ( meta + V )
- select all ( meta + A )
- undo ( meta + Z )
- redo ( meta + Y )
=> Implementing listeners for mac meta key

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
=> [Polyfill]: Removing revealable context menu options that link to non-supported tools

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Quick open and command menu should be disabled via this commit: https://github.com/microsoft/vscode-edge-devtools/pull/131
This PR re-disables the Quick open menu, but leaves the command menu available with filtered commands.  The commands will contain the commands from the available tabs (Only Elements commands when Network is disabled and Elements and Network commands when Network is enabled.)
=> Re-disable quick open menu and filter command menu options

CHANGELOG.md, CONTRIBUTING.md, postBuildStep.ts, scripts/downloadAndExtractEdge.js, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Upgrading to version 85.0.564.40.
Changes:
- Adding `applyRemovePreferencePatch` and `applyDefaultTabPatch`
- `applyRemovePreferencePatch` patches the `removePreference` function such that it does not try to delete objects from `localStorage` which is set to `undefined` in the extension
-`applyDefaultTabPatch` removes the need of `TabbedLocation._defaultTab` which was causing issues with our `applyAppendTabPatch`.
- Removing `applyShowElementsTab`
- removing this patch that sets `_defaultTab` to `elements`
- This is generally unnecessary as it will default to Elements if Network is disabled and we do not want to pigeonhole users to the Elements panel if Network is enabled.
- Updating extension version to `1.1.2`
=> [Update]: Upgrading Edge DevTools version to 85.0.564.40

src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/toolsHost.ts
This PR closes #231 by implementing a `copyText` function within `toolsHost.ts` which overwrites the original `copyText` function implemented in `InspectorFrontendHost`.
Command menu copy functions:
=> [Bug Fix]: Fix command menu copy functions

src/host/polyfills/simpleView.test.ts
SimpleView tests have a bunch of repeated code, namely:
- finding the file
- applying the patch
- checking if the result of the patch is null
- checking for any expected/non-expected strings
This PR creates a `testPatch` function that takes in parameters: `filename: string, patch: (content:string)=>string|null, expectedStrings?: string[], nonExpectedStrings?: string[]` and performs the steps above.
This PR also modifies existing tests to follow this structure:
```
const filePath = "quick_open/quick_open.js";
const patch = SimpleView.applyQuickOpenPatch;
const expectedStrings = ["handleAction(context, actionId) { actionId = null; switch(actionId)"];
await testPatch(filePath, patch, expectedStrings);
```
=> [SimpleView Tests]: Creating testPatch helper function to reduce repeated code

src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/host.ts, src/host/toolsHost.ts
The DevTools window traps keyboard shortcuts inside the iframe, so users who are focused inside the DevTools cannot navigate in/out using `CTRL + PageDown` or `CTRL + PageUp`.  This change implements the next/previous editor shortcut keys within the DevTools window to allow users to easily switch between windows with the next/previous shortcuts.
closes #208
=> [Keyboard Shortcuts]: Adding focus next/previous editor listeners inside dtwindow to quickly switch between panes

src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/host.ts, src/host/toolsHost.ts
This PR adds shortcuts for `workbench.action.focusPreviousGroup` and `workbench.action.focusNextGroup`.  These commands by default in vscode require listening for a second key chord (e.g. `Ctrl + K -> Ctrl + ArrowRight` for `focusNextGroup`).  This structure is now replicated in `host.ts` with the `listenForSecondKeyChord` boolean.
Other changes include improvements to the `focusNextEditor`/`focusPreviousEditor` commands by merging them into one `focusEditor` command with an argument determining direction.
closes #208
=> [Shortcuts]: Add Focus next/previous editor group

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Creating helper function called `replaceInSourceCode` in `simpleView.ts` to help with finding the injection point and replacing code.
```
function replaceInSourceCode(content: string, pattern: RegExp, replacementText: string, keepMatchedText?: KeepMatchedText) {
const match = content.match(pattern);
if (match) {
if (keepMatchedText) {
const matchedText = match[0];
if (keepMatchedText === KeepMatchedText.AtEnd) {
replacementText = `${replacementText}${matchedText}`;
} else {
replacementText = `${matchedText}${replacementText}`;
}
}
return content.replace(pattern, replacementText);
} else {
return null;
}
}
```
This change helps cut down on almost 100 lines of code and simplifies adding a new patch.
Additionally, I have split apart any patches that contained two separate code injections so …
=> [SimpleView]: Create and use helper function to replace code

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
This PR changes revealing workflow for clicking style properties and style sheet links.
Issues:
- VSCode reveals style sheet whenever a style property is clicked
- Clicking on a style sheet in the styles properties section does not reveal anything
Changes:
- VSCode only reveals the style sheet when the user `CTRL + Click` on the style property
- Clicking on a style sheet link in the styles properties section will reveal the style sheet in VSCode.
GIF:
=> [VSCode Revealer]: Fix revealer workflow for style properties sections

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Issue:
- If the Network tool is disabled, the drawer is a blank piece of UI that can be toggled on and off
- The drawer is used to show the Request Blocking tool when the Network tool is enabled
GIF:
Changes:
- Disables drawer toggle when Network tool is disabled
- Will automatically close drawer upon initialization if the Network tool is disabled.
closes #234
=> [Bug Fix]: Disables and hides drawer when Network tool is disabled

package.json
This PR enables the Network Tool by default.
=> [Settings]: Enable Network tool by default

postBuildStep.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/simpleView.ts
Issue:
- Screencast uses a touch cursor, but we aren't targeting mobile devices in the extension
Changes:
- Change cursor to default type for screencast view
closes #104
=> [Screencast]: Change cursor type from touch to default

.gitignore, src/cdpTarget.ts, src/cdpTargetsProvider.test.ts, src/cdpTargetsProvider.ts, src/extension.ts
This PR introduces the functionality of pulling down the target website's favicon when populating the target tree item in the extension side bar.
GIF:
closes #250
=> [Feature]: Show target website favicon in extension sidebar

src/host/polyfills/cssPaddingInline.test.ts, src/host/polyfills/inspectorContentPolicy.test.ts, src/host/polyfills/runtime.test.ts, src/host/polyfills/simpleView.test.ts, src/host/polyfills/textSelection.test.ts, src/test/helpers.ts
This PR moves the `testPatch` function to `helpers.ts` so that other tests inside the `polyfill` directory can use the function.  This helps simplify and standardize testing.
#282
=> [Tests]: Use test helper function for all tests in polyfill directory

package.json, src/extension.test.ts, src/extension.ts
This PR adds a dropdown menu in the extension's title view that contains links to the extension's settings and changelog.
GIF:
closes #255
=> [Feature]: Add dropdown menu in title view containing link to settings and changelog

src/devtoolsPanel.ts, src/test/helpers.ts
This PR closes the VSCode Output channel where the DevTools redirects console output to upon close of the DevTools.  This change prevents the issue where multiple instances of the DevTools will create more and more output channels.
****
closes #291
=> [Bug Fix]: Close DevTools output channel upon closing DevTools

package.json, src/extension.ts, src/test/helpers.ts
Issue:
- This message pops up when users press either the `Open a new tab` or `refresh` buttons at the top before the commands can be registered
Changes:
- added `titleCommandsRegistered` condition to show the `Open a new tab` or `refresh` buttons
- the `titleCommandsRegistered` flag is turned to true once registration for those commands are complete.
closes #277
=> [Bug]: fix *.launch *.refresh not found bug

package.json, src/cdpTargetsProvider.ts
This PR hides service and shared workers behind a settings flag to declutter the target list.
GIF:
closes #276
=> [Settings]: Create setting to show service and shared workers in the target list (will now hide by default)

src/cdpTargetsProvider.ts
When passing in an address beginning with `http`, it will throw this failure:
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```
This PR adds a check to make sure that we are only downloading from `https` to ensure that we are only downloading the favicon from secure sites.
closes #293
=> [Bug]: Adding check for http in favicon download to prevent broken state

src/extension.test.ts, src/extension.ts
Changes in this PR:
- Add event listeners to the browser instance once it's obtained, so we can refresh the side panel when target creation/destruction events are emitted
- Ensure tests still pass by mocking the browser instance's addListener function
=> Side panel auto-refreshes when targets are created or destroyed

scripts/downloadAndExtractEdge.js
donwload-edge script fails on ARM devices on a race condition between extracting the edge.zip and deleting the file. This PR fixes the issue allowing it to finish the extract before deleting.
=> Fixing download-edge script in ARM devices

CHANGELOG.md, README.md, package.json, src/host/polyfills/releaseNoteContent.ts
Removing the dependency to the msjsdiag.debugger-for-edge debugger
=> Removing the dependency to the msjsdiag.debugger-for-edge debugger

postBuildStep.ts, src/host/polyfills/thirdPartyI18n.test.ts, src/host/polyfills/thirdPartyI18n.ts
This PR overrides the list of supported locales on the Devtools as extension currently only support en-US
=> Overriding supported localization

CHANGELOG.md, package-lock.json, package.json
Updating to version 1.1.7 to release some bug fixes:
* **[Bug Fix]**: Retain focus on property after toggling with context menu
[PR #332](https://github.com/microsoft/vscode-edge-devtools/pull/332)
* **[Bug Fix]**: Extension does not work and panel is blank - [PR #342](https://github.com/microsoft/vscode-edge-devtools/pull/342)
=> Updating version 1.1.7

package.json, src/extension.test.ts, src/extension.ts, src/launchDebugProvider.ts, src/utils.test.ts, src/utils.ts
This PR adds explanatory welcome content to the side pane when there are no targets to display. Users are prompted to launch an instance of Edge and configure their launch.json file to streamline the workflow.
Here's how the "getting started" workflow looks with a project that originally has no launch.json:
Summary of the changes:
- Added welcome messages and buttons
- Added 2 new commands to edit and make use of launch.json
- Updated existing tests and added tests for new functions
A second attempt of #351
Closes #337
=> Interactive documentation for side panel (2)

.github/workflows/main.yml
- Ensure that work items are only created when the issue is labeled
- Remove ado_wit, since the WIT is determined within the script
- Added some more events to trigger the script
=> Updates to issue sync action

src/cdpTargetsProvider.ts, src/extension.ts, src/utils.ts, test/extension.test.ts
Adding more button press telemetry:
- Refresh
- View Settings from triple dot menu
- View Changelog from triple dot menu
- Attach to target
- Close target
Other changes:
- Removed calls to `vscode.commands.executeCommand(${SETTINGS_VIEW_NAME}.refresh)` to ensure that all telemetry fires are from the button only.
- Changed those calls to call `cdpTargetsProvider.refresh()` directly - no functional difference.
- Created and exported `setLaunchConfig()` so that `cdpTargetsProvider` can update `launchConfig` when calling `cdpTargetsProvider.refresh()`
- This also used to rely on `vscode.commands.executeCommand(${SETTINGS_VIEW_NAME}.refresh)`
- Fixed some spacing issues in `cdpTargetsProvider.ts` that were bugging me
=> [Telemetry]: Adding telemetry to button presses in title and target view

src/host/polyfills/simpleView.ts, test/host/polyfills/simpleView.test.ts
The accessibility issue is that screen reader users do not hear the success message of the "Toggle property and continue editing selected" context menu option for styles properties:
This is in part due to the same context menu/webview issue that was causing the accessibility bug here: https://github.com/microsoft/vscode-edge-devtools/pull/332
This PR adds an alert call inside the patch created in the PR above so that it will announce the success message.
=> [Accessibility]: Add success alert when selecting 'Toggle property and continue editing selected'

package-lock.json, package.json, src/JsDebugProxyPanelSocket.ts, src/devtoolsPanel.ts, src/extension.ts, src/panelSocket.ts, src/utils.ts, test/devtoolsPanel.test.ts, test/extension.test.ts, test/helpers/helpers.ts, test/utils.test.ts
This Pull request registers a new command for the extension that allows VSCode's JavaScript Debugger to attach the devtools to the currently active debug target.
It also leverages the new CDPProxy that allows our extension to connect to the client using the same websocket as the JsDebugger, giving us the benefits of:
- Appearing as a single debugger to the debug client page
- Allowing us to attach to debugging instances of Edge that are connected via annonymous pipes from VSCode debugger, instead of only remote-debugging-port launched Edge instances
Testing instructions:
To test the new features, Follow the instructions to install the Nightly flight of the JavaScript Debugger into VSCode Insiders from: https://github.com/microsoft/vscode-js-debug#nightly-extension
Then, debug a build from …
=> Add ability to attach to active debug target using shared CDP connection

src/cdpTargetsProvider.ts, src/extension.ts, test/cdpTargetsProvider.test.ts
This PR removes these telemetry events
- `view/list`
- This fires when `getChildren` is called
- `getChildren` is called in many different ways, so this isn't super useful.
- `view/refresh`
- This is called when `refresh()` is called which calls `getChildren`.
- Not entirely useful for the same reason as `view/list` 
- `command/attach`
- This only triggers when the browser instance is first attached to.  We already have `command/launch` to track every new browser target.
- `command/attach/list`
- Same as `command/attach`
- `command/attach/devtools`
- Same as `command/attach`
=> [Telemetry]: Remove unnecessary telemetry

package.json, src/devtoolsPanel.ts, src/extension.ts, src/utils.ts
This PR adds extra parameters to existing telemetry events.  Here are the changes:
- `command/launch`
- added extra parameters `browserType` and `isHeadless`
- `browserType` can be `Default`, `Stable`, `Beta`, `Dev` or `Canary`
- `isHeadless` can be `true` or `false`
- Example: 
- `command/launch: {"viaConfig":"false","browserType":"Default","isHeadless":"false"}`
- `websocket/dispose`
- added extra parameter `sessionTime` which tracks length the DevTools extension was connected to that target
- Example:
- `websocket/dispose: undefined, {"sessionTime":489728.6491000056}`
- `user/buttonPress`
- We now differentiate whether the `.launch` command is triggered through the plus button or the launch instance blue button.
=> [Telemetry]: Implement extra launch parameters and websocket session length

src/extension.ts, src/utils.ts, test/extension.test.ts, test/helpers/helpers.ts, test/utils.test.ts, tsconfig.json
This PR adds telemetry that sends the used file extension types in the user's currently active workspace.  The telemetry is sent upon the activation of the extension.
- `workspace/metadata`
- example:
- `workspace/metadata: undefined, {"css":1,"js":1,"html":1,"json":2,"total":5}`
=> [Telemetry]: Add telemetry for file extension types

postBuildStep.ts, src/common/settingsProvider.ts, src/devtoolsPanel.ts, src/host/polyfills/simpleView.ts, src/host/toolsHost.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts, test/host/polyfills/simpleView.test.ts
Couple of telemetry / screencast related changes in this PR.
- `applyScreencastHeadlessPatch(...)`
- This modifies ScreencastApp constructor to show/hide screencast based on whether the extension's headless mode is enabled or disabled.
- Needed to pipe through the headless extension setting into the `vscodeObject` so we can access it in the DevTools code.
- This also helps set up a `_startTime` property to properly record session duration for `DevTools.ScreencastDuration`
- `applyScreencastTelemetry(...)`
- This patch injects two telemetry events that are fired upon toggling the screencast button
- `DevTools.ScreencastToggle`
- This fires on each button press and shows whether the view is shown / hidden
- Show: `devtools/DevTools.ScreencastToggle: …
=> [Telemetry]: Patching in DevTools telemetry events for screencast duration and toggle + change default toggle state based on headless settings

package.json, src/devtoolsPanel.ts, src/extension.ts, src/utils.ts, test/extension.test.ts, test/helpers/helpers.ts, test/utils.test.ts
This PR implements two telemetry events related to the extension settings:
- `user/settingsChangedAtLaunch`
- This event fires upon extension activation and displays all extension settings that differ from the default value
- Example: `user/settingsChangedAtLaunch: {"enableNetwork":"false","themes":"Light"}, undefined`
- `user/settingsChanged`
- This event fires whenever a user changes a setting related to our extension
- Example: `user/settingsChanged: {"enableNetwork":"false"}, undefined`
Going to try something new and do code explanation via comments. Marking them all as resolved so they are collapsible, but feel free to reply to and/or activate them if you have a question regarding that section.
=> [Telemetry]: Adding extension settings related telemetry

postBuildStep.ts, src/host/polyfills/simpleView.ts, test/host/polyfills/simpleView.test.ts
This PR patches the styles pane to inform users that they may need to resume or refresh the target to get styles information. The CSS domain cannot be enabled when the debugger is paused, which leads to a blank styles pane. This updates the default message to inform users what to do. This does not occur for standalone/inbox devtools as the css domain is always enabled during initialization, before any breakpoints can be hit. However, this can be hit fairly easily using the "inspect button" when VSCode's JS Debugger is currently attached to a target that is paused.
Before:
After:
Addresses #407
=> Patch Styles panel to inform users to resume if debugger paused

package.json, postBuildStep.ts, src/common/settingsProvider.ts, src/devtoolsPanel.ts, src/host/polyfills/releaseNote.ts, src/host/polyfills/releaseNoteContent.ts, src/host/polyfills/simpleView.ts, src/host/toolsHost.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts, test/host/polyfills/releaseNote.test.ts, test/host/polyfills/simpleView.test.ts, test/utils.test.ts
This PR reformats and updates the `releaseNote` patches to work with the new Welcome tab introduced in Edge DevTools version 89.  It also contains new release notes that cover the biggest changes since version 1.1.9 and from the DevTools versions 89, 90 and 91.
=> Transitioning What's New to Welcome tab

src/devtoolsPanel.ts, test/devtoolsPanel.test.ts
This PR adds the feature to switch to another instance of the DevTools if one is currently open.
GIF:
=> [Feature]: Added ability to switch targets with DevTools open

package.json, src/devtoolsPanel.ts
A WiP sourcemapping change was accidentally included in this PR: https://github.com/microsoft/vscode-edge-devtools/pull/406
This PR removes this change.
=> [Revert]: Revert unintended webpack sourcemapping change

examples/sourcemaps.md, package.json, src/devtoolsPanel.ts, src/utils.ts, test/utils.test.ts
This PR updates the `content-src` CSP to allow URLs with `data:` prefixes.  It also updates webpack sourcemapping to account for `webpack://` resource prefixes.
These changes should help improve compatibility of the extension with projects using webpack.
=> [Bug Fix]: Updating webview CSP + webpack sourcemapping overrides

scripts/minifyDevtools.js
This PR adds the ability to skip files that don't work with the uglify.js minification module we are using. This addresses an issue in ResourceLoader.js that was preventing proper source map resolution.
=> Minification: add ability to skip minification on problematic files

postBuildStep.ts, src/host/polyfills/simpleView.ts, test/host/polyfills/simpleView.test.ts
This PR unhides the drawer's close button.
Other related changes:
- Created `applyUnhideRightToolbarElementsPatch` that unhides the network search close button and the close drawer button
- Removed `unHideSearchCloseButton` from `applyInspectorCommonNetworkPatch` and added it to `applyUnhideRightToolbarElementsPatch` to consolidate right toolbar unhiding patching.
- renamed all instances of `unHide` to `unhide`
- updated tests
closes #394
=> [Bug Fix]: Unhide close drawer button

src/utils.ts, test/utils.test.ts
Our previous implementation of the `workspace/metadata` telemetry would send a count of every file extension type in the user's workspace. This created thousands of different properties that needed to be categorized for this telemetry event due to the vast number of file extension types.
To reduce the # of properties for this telemetry event, this PR scopes down to only track the relevant file types.  An example of the new event property would look something like this:
`{"css": 1, "html": 0, "js": 1, "json": 1, "jsx": 1, "mjs": 0, "scss": 0, "totalWorkspaceSize": 10, "ts": 0}`
Note that the `totalWorkspaceSize` property will still track the total # of files, not just the total of relevant file types
=> [Telemetry]: Modifying workspace/metadata telemetry to track only relevant file types

src/devtoolsPanel.ts
Issue:
string.js was removed in Edge 091 but our code still tries to reach to it:
Fix:
Remove string.js references.
=> Removing unused strings.js reference

package.json
Edge Devtools for VSCode does not currently plan to support virtual workspaces. We can always revisit this decision if we find that there is enough user push for it.
=> Disabling virtual workspaces.

src/utils.ts
Currently, Edge devtools is unable to use the JsDebug integration when jsdbug is in a remote workspace. This PR adds a new parameter to the request for a CDP proxy connection to indicate that JsDebug should forward CDP calls to the local UI instance of the Devtools extension.
Addresses #413
More information:
https://github.com/microsoft/vscode-js-debug/issues/1024
https://github.com/microsoft/vscode-js-debug/commit/7afc5b2bb68029296d94d2eb79c0852820e61f10
=> Add "forwardToUi" param when requesting jsdebug proxy connection

src/common/settingsProvider.ts, src/devtoolsPanel.ts
This PR adds support for setting the devtools extension theme if the user switches to a theme that the devtools frontend supports
=> Add theme detection for supported Devtools themes in frame hosted tools

README.md
We are now live with the docs at https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension and this now fixes the link.
=> Fixing the new docs link

package.json, src/devtoolsPanel.ts, src/panelSocket.ts, src/versionSocketConnection.ts, test/devtoolsPanel.test.ts, test/versionDetectionSocket.test.ts
This PR adds the ability for the extension to choose the legacy (inbox) or CDN based connection to a debug target based on it's version.
It adds a new versionDetectionSocket that sends a single message: CDP's browser.getVersion in order to determine which version of the tools to load, then informs the devtoolsPanel and disposes itself
=> Remote CDN connection logic for devtools

src/devtoolsPanel.ts, src/versionSocketConnection.ts, test/versionDetectionSocket.test.ts
This PR updates the browser revision calculation socket to also pass a headless query param to allow the DevTools to know if it is attached to a headless target.
=> Add headless query param support to Cdn DevTools

src/devtoolsPanel.ts
This PR updates our Console output to inform users that it will be deprecated and direct folks to use JSDebugger instead.
=> Deprecate console output in favor of JSDebugger

package.json, src/extension.ts
This PR adds a new section to the extension sidebar, which contains links to documentation and the 'New Issue' page in our repo. It also updates the url in the viewDocumentation command from this repo's README to the official Microsoft documentation.
A few challenges posed by the VSCode Extension API
- [By convention, any command links that are on a line by themselves are displayed as a button](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome), which prevents us from showing these as links instead of buttons
- The initial height of the tree view sections can't be specified (afaik), so the two sections will take up equal amounts of the sidebar the first time the user opens it, which will show a lot of empty space on the bottom section. Afterwards …
=> Add links to documentation/file an issue to sidebar

src/versionSocketConnection.ts, test/versionDetectionSocket.test.ts
This PR updates the min supported version that the extension will attempt to use the CDN to 94.0.988.0, which is the first canary that has all of the migrated polyfills
=> Update min supported version for CDN tools

src/common/styles.css, src/devtoolsPanel.ts, src/host_beta/messageRouter.ts
This PR adds a default message to the DevTools webview that is only seen if the iframe fails to load anything. This is to address the rare case that the CDN fails on first attempt to debug a new browser version
=> Create default landing page for webview in case remote devtools fail to load

src/devtoolsPanel.ts, src/utils.ts, test/devtoolsPanel.test.ts
This addresses #436 by doing a check for whether there is a remote, and if so, being more fluid on the way the files are discovered.
I've tested this on WSL and non-remote (Windows) and it worked as expected,
=> Supporting following CSS links on WSL remotes

.github/ISSUE_TEMPLATE/bug_report.md
Changes iOS as a suggested environment (since I don't believe that one is supported), updates version number sample in #.#.# format, and adds a commented instruction to the user on how to find extension version in VS Code. 
Suggesting this edit because I initially had a hard time finding the version number for the extension when filing a bug, and I accidentally included the version number for the debugger extension instead. 😅
=> Adds instruction on how to include extension version

src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/toolsHost.ts
This PR removes the deprecated console output now that Edge 94 is rolling out to stable
=> Remove deprecated console output

src/screencast/screencast.ts, src/screencast/view.ts
This patch sends `user-agent` overrides to the debug target when device
is changed in standalone screencast.
=> [Screencast] Handle user-agent emulation

package-lock.json, package.json
Updating webhint to version 1.6.3 to fix bug where static analysis squigglies would only underline the first character of the report instead of the entire word
=> [Webhint]: Update version to 1.6.3

src/devtoolsPanel.ts, src/extension.ts, src/screencast/cdp.ts, src/screencastPanel.ts
This PR re-implements these two telemetry events in the new standalone screencast:
- `DevTools.ScreencastToggle`
- This fires on each button press and shows whether the view is shown / hidden
- Show: `devtools/DevTools.ScreencastToggle: {"DevTools.ScreencastToggle.actionCode":"1"}`
- Hide: `devtools/DevTools.ScreencastToggle: {"DevTools.ScreencastToggle.actionCode":"0"}`
- `DevTools.ScreencastDuration`
- This fires when the screencast is toggled off and shows the session time in ms
- `devtools/DevTools.ScreencastDuration: undefined, {"DevTools.ScreencastDuration.duration":1001}`
=> [Telemetry]: Re-implement screencast telemetry

package.json, src/utils.ts
This PR adds an option to enable cors when launching instance.
=> launch Microsoft Edge with specified args

src/screencast/screencast.ts
Fix #642 
Corrects a minor logic error which was causing http:// to always be added on every check.
=> [Screencast]: Fix incorrectly prefixing full URLs with http://

src/extension.ts, src/launchDebugProvider.ts, src/utils.ts, test/helpers/helpers.ts
Also suppress prompting for error reports for missing targets in these cases as switching to `pwa-msedge` is the correct fix.
Displayed warning (shows "edge" or "msedge" depending on actual target type used):
The "Learn More" button opens the VS Code documentation on debugging browsers which discusses the correct target types to use: https://code.visualstudio.com/docs/nodejs/browser-debugging
=> Warn when using deprecated 'edge' or 'msedge' launch types

src/devtoolsPanel.ts, src/extension.ts, src/screencastPanel.ts
Fix #687 
Screencast frames were not being received because the corresponding events were not getting forwarded from js-debug over the proxied CDP connection. Sending the js-debug specific request for events fixes the issue per https://github.com/microsoft/vscode-js-debug/blob/main/CDP_SHARE.md, aligning the screencast panel with the existing behavior for the devtools panel.
=> [Screencast]: Register for CDP events when using with js-debug proxy

src/utils.ts
A review of the `Error while getting the list of targets` failures shows the vast majority are various forms of connection errors beyond the current check (followed by a few explicit misconfigurations). These are already gracefully handled. Removing this specific report as a result since it is not leading to the discovery of underlying issues in the extension.
=> Silently handle target discovery failures

package.json, src/devtoolsPanel.ts
Updates the default value of the headless setting to launch new Edge instances as headless by default, which will automatically trigger the standalone screencast experience. Also fixes opening the screencast when attaching to an existing instance based on whether the instance is headless (instead of the state of the setting).
=> Switch to headless by default

package.json
Open a folder link was solely identifiable using only color, adding a button helps it be more identifiable.
=> fix open folder link to be a button

src/errorReporter.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts
Use a warning as some issues may be transient. Also suggest
checking settings as we've seen some issues are due to
misconfiguration of the extension. Lastly, direct users to a
search of existing issues with the same error message to
discourage filing duplicates.
Example:
=> Refine prompt informing users of errors

.github/stale.yaml
This is the config file that the Stale github app can rely on if we decide to use it on this repo: https://github.com/apps/stale
Here is how the app works:
* It will consider an issue as stale after 7 days of inactivity (this way if we haven't responded to someone within a week, we get a ping).
* Issues that are considered stale are given the label `stale`.
* After 7 more days of inactivity, the issue is closed.
* Issues with label `tracked` are never considered stale.
=> New stalebot config file

src/utils.ts
This fixes the issue where the userDataDir is not found when attempting to launch the Edge instance.  This results in a failure and aborts the launch process.  This only repros when launching the browser instance from our extension (since the failure is from puppeteer and we use puppeteer to launch) and when the user's userDataDir does not exist.
(e.g. `C:\Users\{username}\AppData\Local\Temp\vscode-edge-devtools-userdatadir_9222`)
close #861
=> Bug Fix: create userDataDir if it doesn't exist

src/versionSocketConnection.ts
This patch fixes a bug with the version comparison logic used to
determine which revision of the DevTools frontend to fetch from the CDN.
The previous version comparison logic did not appropriately cast to int
the product could get into a situation where browser version "100" > min_ver.
Fixes #878
=> Fix Min-Browser Version Comparison

src/extension.ts, src/utils.ts, test/utils.test.ts
Fixes #787 
The `webRoot` config was not being considered when mapping a URL to a path on the filesystem. This prevented file links in the devtools from successfully opening files in the editor. The fix is to treat `webRoot` as an entry in `pathMapping`.
This fixes the `webRoot` property in Microsoft Edge DevTools' own extension settings, but the extension isn't currently aware of `webRoot` and `pathMapping` properties found in `launch.json` configs. A separate PR https://github.com/microsoft/vscode-js-debug/pull/1206 plumbs those through to our extension so they will work as expected.
=> Use webRoot config for source path resolution

src/JsDebugProxyPanelSocket.ts, src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/messageRouter.ts
This PR implements the extension side flow for `replayConsoleMessages`. This method stores any console messages until the DevTools indicates it is ready to receive them and then it replays the messages to the DevTools.
Testing this feature completely requires the nightly build of JS-Debug which can be found here: https://github.com/microsoft/vscode-js-debug/blob/main/README.md#nightly-extension
=> [Feature]: Enable console in DevTools

package.json, src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/host/messageRouter.ts
This PR introduces a new setting called `fallbackRevision`.  This setting is updated each time we successfully connect to the DevTools to store the last known working revision. If the DevTools fails to connect to a target, we fallback on using the revision stored in the `fallbackRevision` setting.
This allows users to reliably use the extension offline and when given a faulty revision hash.
=> [Feature]: Save last successful DevTools revision to improve reliability

package-lock.json, package.json
This PR updates the extension to use the latest version of the [vscode-webhint npm package](https://www.npmjs.com/package/vscode-webhint).
=> Update  vscode-webhint to version 1.6.5

src/launchConfigManager.ts, src/launchDebugProvider.ts, test/launchConfigManager.test.ts, test/launchDebugProvider.test.ts
This PR updates the auto-generated launch.json to include two compound configs and three hidden helper configs.
Hidden Configs:
- `Launch Microsoft Edge` - Launches an instance of MSEdge in remote debugging
- `Launch Microsoft Edge in headless mode` - Same as above but in headless mode
- `Open Edge DevTools` - Launches the DevTools and attaches to a URL
Visible Compound Configs:
- `Launch Edge and attach DevTools` - Compounds `Launch Microsoft Edge` and `Open Edge DevTools`
- `Launch Edge in headless mode and attach DevTools ` - Compounds `Launch Microsoft Edge in headless mode` and `Open Edge DevTools`
The end result looks like this:
=> [Launch.json]: Update auto-generated launch.json to use current workflows

src/launchConfigManager.ts
See https://github.com/microsoft/vscode-edge-devtools/pull/927
New config order:
=> [Bug Fix]: Swap compound config order so headless is the first option

package.json, src/common/settingsProvider.ts, src/common/webviewEvents.ts, src/devtoolsPanel.ts, src/extension.ts, src/host/messageRouter.ts, test/devtoolsPanel.test.ts, test/extension.test.ts
This patch removes the CSS Mirroring view from the extension panel and
implements the `toggleCSSMirrorContent` host method which toggles the
CSS Mirror content feature in the extensions settings.
=> [CSS Mirroring] Support CSS Mirroring Enablement from DevTools frontend

src/launchConfigManager.ts, test/launchConfigManager.test.ts
Issue:
- Due to the LaunchConfigManager changes in https://github.com/microsoft/vscode-edge-devtools/pull/927, configuring existing `launch.json` files would result in either duplicate or missing entries.
Changes:
- Improve logic for checking for missing configs
- We now cross reference the user's `launch.json` configuration with our expected configurations.  This allows us to add only the missing configs.
- This improvement is also passed into the logic to determine if a user's `launch.json` configuration is supported or not unsupported.
Things to test:
- Try running `Configure launch.json` against various `launch.json` files.
- this includes missing `launch.json`, `launch.json` with some of the configurations, `launch.json` with none of the configurations, etc.
- With the different …
=> [LaunchConfigManager]: Improve logic for configuring existing launch.json

src/devtoolsPanel.ts, src/launchConfigManager.ts, src/screencastPanel.ts, test/helpers/helpers.ts
This PR introduces the behavior where the debugging session ends for a headless target when both the DevToolsPanel and Screencast are disposed. This only stops the debugging session if the active session name matches our launch Edge headless config.
Changes:
- add logic to both DevToolsPanel and ScreencastPanel `dispose` methods that will stop debugging session if the target is headless and both panels are closed.
=> Stop debugging session on a headless target when both DevToolsPanel and Screencast are closed

src/screencast/screencast.ts
The screencast wrapper previously used to calculate height would be stretched vertically by taller canvas content, such that when shrinking the screencast panel it never correctly shrunk the content.
Fixed by using an element higher up the ancestor chain as the base for sizing. However, this element includes the toolbar so we have to adjust the resulting size by the toolbar height to compensate.
=> Fix recalculating screencast height when shrinking vertically

src/devtoolsPanel.ts
Currently if a user makes local edits to a CSS file, then makes a change in DevTools without saving and rebuilding, the unsaved changes will be overwritten when mirroring CSS content.
This change adds a check to verify the content in the editor either (1) doesn't have any unsaved changes or (2) has only unsaved changes that match what was previously mirrored from DevTools. If these conditions are not met, then the change from DevTools will not be mirrored and a warning notification will be displayed to the user asking them to save and reload the target page (undoing local changes and retrying will also work).
=> Warn and pause mirroring CSS if it would override local edits

package.json, src/common/settingsProvider.ts, src/common/webviewEvents.ts, src/devtoolsPanel.ts, test/common/settingsProvider.test.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts, test/utils.test.ts
The extension's DevTools theme would prioritize the user's VSCode theme over the extension's theme settings in VSCode which rendered it useless in most cases.  The only time it would take precedence is if the user had a non-supported vscode theme that we could not apply to the DevTools. To fill in that functionality, this PR falls back to detecting whether the custom theme is light/dark and sets the DevTools theme to the default light/dark theme accordingly.
closes https://github.com/microsoft/vscode-edge-devtools/issues/531
=> [Settings]: Remove theme settings + add auto-detection for light/dark theme for unsupported vscode themes

src/screencast/screencast.ts
Also continues to correctly map coordinates for high DPI displays.
Notably Electron appears to have a long-standing bug where `window.devicePixelRatio` is not always correct. Furthermore, this value (correctly) incorporates both the VS Code zoom level and device zoom level (but the browser only uses the latter). This change avoids issues with this API by deriving the mapping from the difference in sizes between our expected and actual layout width. It also avoids the API when deciding whether to update emulation settings by comparing the ratio of width/height to the expected ratio instead of trying to derive the exact expected dimensions.
Fixes #924
=> Fix mapping input coordinates when VS Code is zoomed

src/utils.ts
For a while we have been sending telemetry events to our pipeline even when developing. Our original flag for determining whether we were running in production or in development was to use:
`vscode.env.machineId !== 'someValue.machineId'`
This is outdated as `vscode.env.machineId` will no longer point to `someValue.machineId` while developing. This PR updates our code to use `context.extensionMode` instead.
See the [ExtensionMode enum](https://github.com/microsoft/vscode/blob/c20b68a62d198e73df34de5f95671eb63c8b5ff2/src/vs/workbench/api/common/extHostTypes.ts#L3389) for details on each context.extensionMode values
=> [Telemetry]: Use DebugTelemetryReporter for extension development

src/screencast/screencast.ts, src/screencast/view.css, src/screencast/view.ts
Previously these would end up clipped to the available space, making part of the screen inaccessible.
=> Fix scaling down emulated devices to fit available space

src/screencast/dimensionComponent.ts, src/screencast/screencast.ts, src/screencast/view.css
Cleaned up some CSS so heights would be consistent to avoid pushing the emulation bar down (and some minor additional touches to align the top toolbar more closely with the design mocks). Plumbed offsets for the emulation and toolbar heights through the dimension component when in responsive mode. Set the correct initial responsive state and width/height.
=> Fix resizing and scaling screencast

src/versionSocketConnection.ts
Use the revision of DevTools from the current Edge Dev channel for all targets less than 102.
Ensures CSS mirroring across source-maps is present regardless of the target version of Edge.
Newer versions of Edge will continue to use their own DevTools revision.
=> Use Edge 102 DevTools as min version for sourcemap support

src/screencast/view.css
=> Fix padding around 'x' icon in Dimension component

src/versionSocketConnection.ts
Avoids a known issue with CSS source-mapped mirroring in Canary.
A follow-up PR will narrow the range once a new Canary is available with a fix.
=> Use 'known good' revision for all current Edge versions

src/screencast/screencast.ts
Enables navigating to local paths copied from elsewhere (similar to what the browser does) so the user doesn't have to convert the path to a `file://` url manually.
=> Support file system paths in screencast address bar

package.json, src/common/settingsProvider.ts, src/devtoolsPanel.ts, src/extension.ts
Effectively removes the old screencast in favor of always using the standalone screencast implementation.
=> Remove standalone screencast setting and related code

package.json, src/extension.ts, src/launchDebugProvider.ts, src/utils.ts, test/launchDebugProvider.test.ts
The `edge` and `msedge` target types should no longer be used now that the "Debugger For Microsoft Edge" extension has been removed from VS Code in favor of jsdebug (which uses `pwa-msedge`). While the legacy extension was still in the marketplace we warned about the deprecation of these target types. Now that it's been removed we can remove support entirely.
=> Remove support for legacy 'edge' and 'msedge' debugger types

package.json, src/devtoolsPanel.ts, src/utils.ts, src/versionSocketConnection.ts
This primarily needs to hold the most recent successful hash and does not need to be configured by the user.
=> Move CDN fallback revision from settings to globalState

package.json, src/common/settingsProvider.ts, src/devtoolsPanel.ts, src/extension.ts, src/utils.ts, test/devtoolsPanel.test.ts
Leaves the checkbox in the DevTools as the primary UI for toggling state.
Also keeps the command for toggling state and fixes it to work when invoked from the command menu.
=> Move CSS mirror editing status from settings to globalState

package.json
Prior removal appears to have been lost during rebase/merge of #1017
=> Remove registration for obsolete network setting

src/utils.ts, src/versionSocketConnection.ts
Zip containing side-loadable VSIX for testing:
[vscode-edge-devtools-app-panel.zip](https://github.com/microsoft/vscode-edge-devtools/files/8673587/vscode-edge-devtools-app-panel.zip)
Fix #1014
=> Bump min DevTools version to include the Application panel

src/devtoolsPanel.ts, src/screencast/view.css, src/screencast/view.ts, src/screencastPanel.ts
This PR changes the "Open DevTools" button on the screencast to be "Toggle DevTools"
DevTools Closed:
DevTools Open:
closes #996
=> [Screencast]: Change Open DevTools button to Toggle DevTools

src/devtoolsPanel.ts
Issue:
- Whenever we get a CSS mirror event while the targeted CSS file is not in sync with the DevTools' copy, we display a warning saying that CSS mirroring will not work.
- This can be spammy especially when using sliders to modify CSS values
Changes:
- Move toast notification logic into a helper and track the state of whether the notification is active or not.
- Prevent refires if the css sync warning notification is active.
Before:
After:
=> [Bug Fix]: Stop CSS Mirroring warning from re-firing if active

src/common/webviewEvents.ts, src/screencast/cdp.ts, src/screencast/input.ts, src/screencast/screencast.ts, src/screencastPanel.ts, test/devtoolsPanel.test.ts
This PR implements text-only clipboard functionality to the screencast. We achieve this functionality in this PR through these steps:
Scenario: Copying text from the screencast and pasting it outside screencast
1. We add a `clipboardRequests` set to `cdp.ts` to track request/response ids of CDP messages that relate to clipboard interaction
2. We register a clipboard handler function called `onSaveToClipboard` from `screencast.ts` on `cdp.ts` to handle incoming clipboard responses
3. We send a CDP call to `Runtime.evaluate` and run `document.getSelection().toString()` to request the selected text and store the request ID to `clipboardRequests`
4. When we get a response ID that matches an ID in `clipboardRequests`, we call the `onSaveToClipboard` function and delete the ID from the …
=> [Screencast]: Add text-only clipboard functionality

src/cdpTarget.ts
Issue:
- Screen reader users have no indication that action button items are available on each CDPTarget treeitem
Changes:
- Adding verbose label to each tree item. 
- Items that are expandable/collapsible are identified as CDPTargets and contain the action button list label.
- Items that are not expandable/collapsible are identified as descriptor tree items and only contain the base label
- The base label is `${this.label}: ${this.description}`.
- Example:
- `this.label` = "type"
- `this.description` = "page"
- ![image](https://user-images.githubusercontent.com/14304598/169610560-4264ac9e-fffb-4e59-a4c9-19fae5c5b572.png)
=> [Accessibility]: Add verbose label to CDPTargets to indicate existence of action buttons on tab

src/extension.ts, src/launchDebugProvider.ts
Issue:
- If a user does not have an existing `launch.json` and selects `Microsoft Edge Tools` as the debug session, we display a `"No supported launch config was found"` error message.
Changes:
- Handle the no-config case in `launchDebugProvider.ts` similar to this mock debugger code snippet:
https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L164
Repro:
- In VSCode, press File -> New Window
- Press F5
- Select "Microsoft Edge Tools" as the environment
Expected:
Some DevTools related debug session will be launched
Actual:
An error toast pops up.
=> [Bug fix]: Route no config debug session to default launch experience

src/extension.ts
Issue:
- `pwa-msedge`'s  `url` property requires `file://` to prefix the URL for local files when on MacOS.
Changes:
- Adding `file://` to the selected html file's path for all platforms (fixes MacOS, Win works w/ and w/o the prefix)
=> [Bug Fix]: Fix context menu entrypoint for MacOS

src/extension.ts
The prior approach to splitting entries on `:` resulted in `undefined`
entries being passed to the language client which caused the language
client and server to fail during startup.
=> Ensure non-undefined document selectors are passed to language client

src/common/settingsProvider.ts
Fixes #1093
The fallback switch used to set `theme` was missing breaks / would always fall through to `default`.
Additionally, updated comments for clarity.
=> [BugFix] Fix theme fallback being always default systemPreferred

package-lock.json, package.json
This PR updates the vscode-webhint dependency to versio `2.1.2` which contains,
**Breaking change: with this PR the required `node` version goes up to 14.0**
Adds quick-fixes to the extension-vscode package, this allows it to show 3 new context-menu
suggestions in the Microsoft Edge Devtools extension. These items are:
Ignore "hint"
Ignore "problem"
Edit .hintrc
Applies recommended code fixes to specific problems reported by webhint.
Fix #1065
Fix #973
=> Breaking: Introducing quickfixes and autofix for webhint reported issues

test/cdpTargetsProvider.test.ts
**Issue:**
` CDPTargetsProvider › check if favicons are downloaded and cleared correctly `
was failing in the CI pipeline
**Root:**
A URL used in the test changed
**Fix:**
Change the URL to point to the new location instead of the redirected location.
=> Fix URL in favicon test

.github/workflows/main.yml
Area paths changed in the Edge ADO instance. We need to update the one we use in this repository's workflow.
=> Adapt the ADO mirroring workflow to the new area paths

package-lock.json, package.json
Updating vscode-webhint version to `2.1.10` to bring some code fixes and the `css-reflows` hint.
=> Updating vscode-webhint version to 2.1.10

package.json, src/extension.ts
Fixes #1145 
- Change `OK` Button for `Remind me later`
- Add `Don't show again` Button, as well as a cached setting that is validated before showing the dialog again. 
- Changes `Disable` for `Disable extension`
Current behavior
New behavior:
=> Updates Webhint install failure notification

CHANGELOG.md, package-lock.json, package.json
Updating version
* **[Bug Fix]**: Adding dashes for passing arguments to scripts  - [PR #1624](https://github.com/microsoft/vscode-edge-devtools/pull/1624)
* **[Feature]**: Reducing size of extension bundle (Produce production builds by default) - [PR #1598](https://github.com/microsoft/vscode-edge-devtools/pull/1598)
* **[Feature]**: Updating vscode-webhint version to 2.1.10  - [PR #1560](https://github.com/microsoft/vscode-edge-devtools/pull/1560)
* **[Bug Fix]**: Changed screencast label to toggle browser to comply with docs  - [PR #1331](https://github.com/microsoft/vscode-edge-devtools/pull/1331)
=> Updating version to 2.1.3

src/utils.ts, test/utils.test.ts
Extension was failing to relaunch on headless. This was due to the host responding with `Using unsafe HTTP verb GET to invoke /json/new. Recommended way is to use PUT`. This PR fixes the issue and adds a test to avoid regression.
Fix #1978
=> Fixing relaunch scenario on headless

src/versionSocketConnection.ts
This PR patches an issue where the icons are being displayed as white squares. The issue is still being root caused but with this patch Edge Devtools version 122+ will default to last working version 121
=> Patch for missing icons

CHANGELOG.md, package-lock.json, package.json
* **[Bug Fix]**: Fixing relaunch scenario on headless - [PR #1979](https://github.com/microsoft/vscode-edge-devtools/pull/1979)
* **[Bug Fix]**: Patch for missing icons - [PR #2045](https://github.com/microsoft/vscode-edge-devtools/pull/2045)
* **[Bug Fix]**: Updating fallback version to 120 - [PR #2046](https://github.com/microsoft/vscode-edge-devtools/pull/2046)
=> Update to version 2.1.5

src/devtoolsPanel.ts, src/utils.ts, src/versionSocketConnection.ts, test/devtoolsPanel.test.ts, test/helpers/helpers.ts
This PR introduces two different ways to fallback to the devtools version displayed by the extension:
Before:
We got the version from the storage, if that did not existed or failed, we got the one from the browser and if that failed we got the one from the CDN. This whole process was async and could take up to ~5s leaving the users with the question if the tool was working or not.
After:
User has the ability to select the fallback chain by selecting the browser flavor. If the user wants a specific version (browserFlavor) the extension will behave in the same way as before, otherwise the first thing we will try to get is a working version of the tools from the CDN fallback address. This process takes less than 1s, making it faster for most of the users
=> Feature: Sets different fallback chains.

src/launchDebugProvider.ts, test/launchDebugProvider.test.ts
See this link for details. https://code.visualstudio.com/api/references/vscode-api#DebugConfigurationProvider → resolveDebugConfigurationWithSubstitutedVariables
This commit fixes the [issue](https://github.com/microsoft/vscode-edge-devtools/issues/2472) that variables in debug configs are not resolved, and instead passed as-is to msedge.exe. Using the proper VS Code API easily solves it.
=> Use substituted config instead of raw

package-lock.json, src/extension.ts, test/extension.test.ts
This PR adds a new argument `launchUrl` to the `vscode.commands.registerCommand` method in the `extension.ts` file.
Close #2677 #1768
=> Adding launchURL argument for the vscode-edge-devtools.launch command
